In [ ]:
import numpy as np
import cv2

 Step 1: Load and Preprocess Image

In [ ]:
img = cv2.imread('/content/sample_data/62a8216a3923c0f0beabb1185c7e32b8.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
resized = cv2.resize(gray, (3, 5))
normalized_input = resized / 255.0

In [ ]:
X = normalized_input.reshape(1, 15)

Step 2: Set Target Output (Binary classification example)

In [ ]:
Y = np.array([[1]])

Step 3: Define Sigmoid Functions

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_deriv(x):
    return x * (1 - x)

Step 4: Initialize Weights

In [ ]:
np.random.seed(1)
input_dim = X.shape[1]
hidden_dim = 6
output_dim = 1

weights_input_hidden = 2 * np.random.random((input_dim, hidden_dim)) - 1
weights_hidden_output = 2 * np.random.random((hidden_dim, output_dim)) - 1

Step 5: Train Network with Backpropagation

In [ ]:
for epoch in range(10000):
    # Forward Pass
    hidden_input = np.dot(X, weights_input_hidden)
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, weights_hidden_output)
    final_output = sigmoid(final_input)

    # Error
    output_error = Y - final_output
    output_delta = output_error * sigmoid_deriv(final_output)

    hidden_error = output_delta.dot(weights_hidden_output.T)
    hidden_delta = hidden_error * sigmoid_deriv(hidden_output)

    # Weight Updates
    weights_hidden_output += hidden_output.T.dot(output_delta)
    weights_input_hidden += X.T.dot(hidden_delta)


Step 6: Output Prediction


In [ ]:
print("5x3 Grayscale Matrix (Normalized):\n", normalized_input)
print("\nPredicted Output:", final_output)

5x3 Grayscale Matrix (Normalized):
 [[0.09803922 0.14509804 0.09411765]
 [0.19215686 0.98039216 0.03137255]
 [0.21960784 0.94117647 0.27058824]
 [0.04705882 0.75686275 0.34117647]
 [0.09411765 0.24705882 0.1372549 ]]

Predicted Output: [[0.99570989]]
